---
dataset_name: CitationFull
model_name: SimpleGCN
dataset_kwargs:
  name: DBLP
distributed_algorithm: fed_gnn
epoch: 1
learning_rate: 0.001
weight_decay: 0
round: 500
worker_number: 100
algorithm_kwargs:
  share_node_feature: true
  share_init_node_feature: false
