---
dataset_name: Yelp
model_name: TwoGCN
distributed_algorithm: fed_gcn
epoch: 1
learning_rate: 0.001
weight_decay: 0
round: 50
worker_number: 50
use_amp: false
algorithm_kwargs:
  share_feature: false
  batch_number: 10
  edge_drop_rate: 0.99
extra_hyper_parameters:
  num_neighbor: 10
