---
dataset_name: MNIST
model_name: LeNet5
distributed_algorithm: fed_avg
optimizer_name: SGD
worker_number: 10
batch_size: 64
round: 20
learning_rate_scheduler: CosineAnnealingLR
epoch: 2
learning_rate: 0.01
...
