---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: sign_SGD
distribute_init_parameters: false
optimizer_name: SGD
worker_number: 10
round: 1
learning_rate_scheduler: CosineAnnealingLR
epoch: 100
batch_size: 64
learning_rate: 0.1
parallel_number: 2
cache_transforms: true
use_amp: false
log_level: INFO
...
