---
dataset_name: IMDB
model_name: TransformerClassificationModel
distributed_algorithm: sign_SGD
distribute_init_parameters: false
optimizer_name: SGD
worker_number: 10
round: 1
learning_rate_scheduler: CosineAnnealingLR
epoch: 100
batch_size: 64
learning_rate: 0.01
parallel_number: 2
cache_transforms: true
use_amp: false
log_level: INFO
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
...
