---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: fed_paq
optimizer_name: SGD
worker_number: 100
round: 100
batch_size: 64
learning_rate_scheduler: CosineAnnealingLR
epoch: 5
learning_rate: 0.1
algorithm_kwargs:
  random_client_number: 50
...
