---
dataset_name: CIFAR100
model_name: densenet40
distributed_algorithm: fed_paq
optimizer_name: SGD
worker_number: 50
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
batch_size: 64
learning_rate: 0.1
algorithm_kwargs:
  random_client_number: 25
...
