---
dataset_name: IMDB
model_name: TransformerClassificationModel
distributed_algorithm: fed_avg
optimizer_name: SGD
worker_number: 10
batch_size: 64
round: 100
learning_rate_scheduler: CosineAnnealingLR
epoch: 5
learning_rate: 0.01
dataset_kwargs:
  max_len: 300
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
