---
dataset_name: CIFAR100
model_name: densenet40
distributed_algorithm: single_model_afd
optimizer_name: SGD
cache_transforms: true
worker_number: 10
round: 100
learning_rate_scheduler: CosineAnnealingLR
epoch: 5
batch_size: 64
learning_rate: 0.1
parallel_number: 2
use_amp: false
log_level: INFO
algorithm_kwargs:
  random_client_number: 5
  dropout_rate: 0.3
...
