---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: single_model_afd
optimizer_name: SGD
worker_number: 10
round: 100
batch_size: 64
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.1
algorithm_kwargs:
  random_client_number: 5
  dropout_rate: 0.3
...
