---
dataset_name: IMDB
model_name: TransformerClassificationModel
distributed_algorithm: single_model_afd
optimizer_name: SGD
worker_number: 100
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
batch_size: 64
learning_rate: 0.01
algorithm_kwargs:
  random_client_number: 50
  dropout_rate: 0.3
dataset_kwargs:
  max_len: 300
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
