---
dataset_name: IMDB
model_name: TransformerClassificationModel
distributed_algorithm: fed_paq
optimizer_name: SGD
cache_transforms: true
worker_number: 10
round: 100
learning_rate_scheduler: CosineAnnealingLR
epoch: 5
batch_size: 64
learning_rate: 0.01
parallel_number: 3
use_amp: true
log_level: INFO
algorithm_kwargs:
  random_client_number: 5
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
...
